version: 2
jobs:
  bobby:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run echo "Hello"
  
  sally:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run echo "Hello"
workflows:
  version: 2
  bobby_sally:
    jobs:
      - bobby
      - sally

# 11