version: 2
jobs:
  bobby:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run echo "Hello"
  
  sally:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "npm installing"
      - run: CI=true npm run build
  test:
    docker:
     - image: circleci/node:8.9
    steps:
      - checkout
      - run: npm install
      - run: npm test
  hithere:
  docker:
     - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "Hello"
workflows:
  version: 2
  build_test_lint:
    jobs:
      - build
      - hithere
      - test:
        requires:
          - hithere

# 11